### PR TITLE
Work on the views

### PR DESCRIPTION
**Pull request by davidgtonge**
I've adjusted the initial view to match the wireframe.
I've also started on the board view. Its currently working using a simple prompt rather than a modal box to change category. Still quite a bit to do, but its coming together.

I'm submitting as a pull request rather than pushing directly to the repo to ease discussion about the updated code. 

Please feel free to merge / refactor / edit as you see fit.

### CODE REVIEW

**Comment by afeld** [comment]
I'll take a look in a couple hours, but may just get up early to try and finish this thing.

**Comment by caseywebdev** [comment]
I like it :+1: I feel like this kanban would be a lot more useful if we merged the repo management and issue management to the same view.

**Comment by afeld** [comment]
Agreed, though it is nice to demonstrate the difference in page "switching" vs. a view that remains forever.  Otherwise I'm not sure how we'd demonstrate how to use `view.destroy()`.

**Comment by caseywebdev** [comment]
We can implement some modal views that are one-and-done, that would show off `destroy`.

**Comment by afeld** [comment]
How do people feel about including Bootstrap?  I would prefer to have as little extra in the repo as possible so we don't distract from our core competency, but I suppose it's pretty lightweight.

**Pull request merged**
